/**
 * generate-fixtures.ts
 *
 * Generates AI-assisted search test cases for the Deezer API.
 * Currently uses a mock LLM response — replace the `callLLM` function
 * with a real Anthropic API call to go live.
 *
 * Usage:
 *   npx ts-node scripts/generate-fixtures.ts
 *
 * Output:
 *   fixtures/ai-generated-search-cases.json
 *
 * Generated by Claude Sonnet 4.6
 */

import * as fs from 'fs';
import * as path from 'path';
import { z } from 'zod';

// ---------------------------------------------------------------------------
// Schema — same shape as search-cases.json
// ---------------------------------------------------------------------------

const SearchCaseSchema = z.object({
  query: z.string().min(1),
  minResults: z.number().int().min(0),
  category: z.string().optional(),
});

const SearchCasesSchema = z.array(SearchCaseSchema);

type SearchCase = z.infer<typeof SearchCaseSchema>;

// ---------------------------------------------------------------------------
// Prompt sent to the LLM
// ---------------------------------------------------------------------------

const SYSTEM_PROMPT = `You are a QA expert specialising in API testing.
Your task is to generate diverse search test cases for the Deezer public search API.
Return ONLY a valid JSON array. No markdown, no explanation, no trailing text.

Each item must follow this exact shape:
{ "query": string, "minResults": number, "category": string }

Rules:
- minResults must be 0 when the query is expected to return no results, otherwise use 1.
- Each category MUST be unique across all items.
- Use precise subcategories with kebab-case, for example:
    multilingual-japanese, multilingual-arabic, multilingual-russian,
    special-characters-slash, special-characters-unicode-symbols,
    accented-characters-french, accented-characters-nordic,
    short-query-single-char, short-query-common-word,
    zero-results-random-string, zero-results-numeric,
    artist-name, genre-jazz, genre-classical
- Do not duplicate queries already in the existing fixtures.
`;

const USER_PROMPT = `
Existing fixtures (do not duplicate):
[
  { "query": "daft punk",           "minResults": 10 },
  { "query": "Björk",               "minResults": 1  },
  { "query": "154651154alaphafa",   "minResults": 0  }
]

Generate 10 new and varied test cases.
`;

// ---------------------------------------------------------------------------
// Mock LLM — replace with real Anthropic call when ready
// ---------------------------------------------------------------------------

async function callLLM(_systemPrompt: string, _userPrompt: string): Promise<string> {
  // -------------------------------------------------------------------
  // 🔌 TO PLUG IN THE REAL API, replace this function body with:
  //
  // const response = await fetch('https://api.anthropic.com/v1/messages', {
  //   method: 'POST',
  //   headers: {
  //     'Content-Type': 'application/json',
  //     'x-api-key': process.env.ANTHROPIC_API_KEY!,
  //     'anthropic-version': '2023-06-01',
  //   },
  //   body: JSON.stringify({
  //     model: 'claude-sonnet-4-6',
  //     max_tokens: 1000,
  //     system: _systemPrompt,
  //     messages: [{ role: 'user', content: _userPrompt }],
  //   }),
  // });
  // const data = await response.json();
  // return data.content[0].text;
  // -------------------------------------------------------------------

  console.log('ℹ️  Using mock LLM response (no API key required)');

  return JSON.stringify([
    { query: "AC/DC",                minResults: 1,  category: "special-characters-slash"    },
    { query: "坂本龍一",              minResults: 1,  category: "multilingual-japanese"       },
    { query: "Иван Купала",          minResults: 1,  category: "multilingual-russian"        },
    { query: "أم كلثوم",             minResults: 1,  category: "multilingual-arabic"         },
    { query: "a",                    minResults: 1,  category: "short-query-single-char"     },
    { query: "!!",                   minResults: 0,  category: "special-characters-symbols"  },
    { query: "jazz",                 minResults: 1,  category: "genre-jazz"                  },
    { query: "Beyoncé",              minResults: 1,  category: "accented-characters-french"  },
    { query: "xzqjfkwpvmblhtrsdyn",  minResults: 0,  category: "zero-results-random-string" },
    { query: "Miles Davis",          minResults: 1,  category: "artist-name"                 },
  ]);
}

// ---------------------------------------------------------------------------
// Validation
// ---------------------------------------------------------------------------

function validateAndParse(raw: string): SearchCase[] {
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch (err) {
    throw new Error(`LLM response is not valid JSON:\n${raw}`);
  }

  const result = SearchCasesSchema.safeParse(parsed);
  if (!result.success) {
    throw new Error(`Zod validation failed:\n${JSON.stringify(result.error.format(), null, 2)}`);
  }

  return result.data;
}

function validateUniqueness(cases: SearchCase[]): void {
  const categories = cases.map(c => c.category).filter(Boolean);
  const duplicates = categories.filter((c, i) => categories.indexOf(c) !== i);
  if (duplicates.length > 0) {
    throw new Error(`Duplicate categories detected: ${[...new Set(duplicates)].join(', ')}`);
  }
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
  console.log('🤖 Generating AI-assisted search fixtures...\n');

  const raw = await callLLM(SYSTEM_PROMPT, USER_PROMPT);
  const cases = validateAndParse(raw);
  validateUniqueness(cases);

  console.log(`✅ ${cases.length} cases validated by Zod\n`);
  cases.forEach(c =>
    console.log(`  [${c.category ?? 'unknown'}] "${c.query}" → minResults: ${c.minResults}`)
  );

  const outputPath = path.resolve(__dirname, '../fixtures/ai-generated-search-cases.json');
  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, JSON.stringify(cases, null, 2), 'utf-8');

  console.log(`\n📄 Written to: ${outputPath}`);
}

main().catch(err => {
  console.error('❌ Error:', err.message);
  process.exit(1);
});