/**
 * generate-fixtures.ts
 *
 * Generates AI-assisted search test cases for the Deezer API.
 * Currently uses a mock LLM response — replace the `callLLM` function
 * with a real Anthropic API call to go live.
 *
 * Usage:
 *   npx ts-node scripts/generate-fixtures.ts
 *
 * Output:
 *   fixtures/ai-generated-search-cases.json
 * 
 * Generated by Claude Sonnet 4.6
 */

import * as fs from 'fs';
import * as path from 'path';
import { z } from 'zod';

// ---------------------------------------------------------------------------
// Schema — same shape as search-cases.json
// ---------------------------------------------------------------------------

const SearchCaseSchema = z.object({
  query: z.string().min(1),
  minResults: z.number().int().min(0),
  category: z.string().optional(), // extra metadata kept for documentation
});

const SearchCasesSchema = z.array(SearchCaseSchema);

type SearchCase = z.infer<typeof SearchCaseSchema>;

// ---------------------------------------------------------------------------
// Prompt sent to the LLM
// ---------------------------------------------------------------------------

const SYSTEM_PROMPT = `You are a QA expert specialising in API testing.
Your task is to generate diverse search test cases for the Deezer public search API.
Return ONLY a valid JSON array. No markdown, no explanation, no trailing text.

Each item must follow this exact shape:
{ "query": string, "minResults": number, "category": string }

Rules:
- minResults must be 0 when the query is expected to return no results, otherwise use 1.
- Cover as many of the following categories as possible:
    multilingual, special_characters, short_query, empty_like, zero_results,
    artist_name, genre, accented_characters, numeric, unicode_symbols
- Do not duplicate queries already in the existing fixtures.
`;

const USER_PROMPT = `
Existing fixtures (do not duplicate):
[
  { "query": "daft punk",           "minResults": 10 },
  { "query": "Björk",               "minResults": 1  },
  { "query": "154651154alaphafa",   "minResults": 0  }
]

Generate 15 new and varied test cases.
`;

// ---------------------------------------------------------------------------
// Mock LLM — replace with real Anthropic call when ready
// ---------------------------------------------------------------------------

async function callLLM(_systemPrompt: string, _userPrompt: string): Promise<string> {
  // -------------------------------------------------------------------
  // 🔌 TO PLUG IN THE REAL API, replace this function body with:
  //
  // const response = await fetch('https://api.anthropic.com/v1/messages', {
  //   method: 'POST',
  //   headers: {
  //     'Content-Type': 'application/json',
  //     'x-api-key': process.env.ANTHROPIC_API_KEY!,
  //     'anthropic-version': '2023-06-01',
  //   },
  //   body: JSON.stringify({
  //     model: 'claude-sonnet-4-6',
  //     max_tokens: 1000,
  //     system: _systemPrompt,
  //     messages: [{ role: 'user', content: _userPrompt }],
  //   }),
  // });
  // const data = await response.json();
  // return data.content[0].text;
  // -------------------------------------------------------------------

  console.log('ℹ️  Using mock LLM response (no API key required)');

  return JSON.stringify([
    { query: "AC/DC",               minResults: 1,  category: "special_characters"   },
    { query: "Sigur Rós",           minResults: 1,  category: "accented_characters"  },
    { query: "坂本龍一",             minResults: 1,  category: "multilingual"         },
    { query: "Иван Купала",         minResults: 1,  category: "multilingual"         },
    { query: "أم كلثوم",            minResults: 1,  category: "multilingual"         },
    { query: "a",                   minResults: 1,  category: "short_query"          },
    { query: "!!",                  minResults: 0,  category: "unicode_symbols"      },
    { query: "1234567890",          minResults: 0,  category: "numeric"              },
    { query: "jazz",                minResults: 1,  category: "genre"                },
    { query: "bossa nova",          minResults: 1,  category: "genre"                },
    { query: "Beyoncé",             minResults: 1,  category: "accented_characters"  },
    { query: "the",                 minResults: 1,  category: "short_query"          },
    { query: "xzqjfkwpvmblhtrsdyn", minResults: 0,  category: "zero_results"        },
    { query: "Miles Davis",         minResults: 1,  category: "artist_name"          },
    { query: "Ólafur Arnalds",      minResults: 1,  category: "accented_characters"  },
  ]);
}

// ---------------------------------------------------------------------------
// Validation
// ---------------------------------------------------------------------------

function validateAndParse(raw: string): SearchCase[] {
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch (err) {
    throw new Error(`LLM response is not valid JSON:\n${raw}`);
  }

  const result = SearchCasesSchema.safeParse(parsed);
  if (!result.success) {
    throw new Error(`Zod validation failed:\n${JSON.stringify(result.error.format(), null, 2)}`);
  }

  return result.data;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
  console.log('🤖 Generating AI-assisted search fixtures...\n');

  const raw = await callLLM(SYSTEM_PROMPT, USER_PROMPT);
  const cases = validateAndParse(raw);

  console.log(`✅ ${cases.length} cases validated by Zod\n`);
  cases.forEach(c =>
    console.log(`  [${c.category ?? 'unknown'}] "${c.query}" → minResults: ${c.minResults}`)
  );

  const outputPath = path.resolve(__dirname, '../fixtures/ai-generated-search-cases.json');
  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, JSON.stringify(cases, null, 2), 'utf-8');

  console.log(`\n📄 Written to: ${outputPath}`);
}

main().catch(err => {
  console.error('❌ Error:', err.message);
  process.exit(1);
});